env:
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-restricted-syntax: 0
  arrow-body-style: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
